Repository qonto/database-monitoring-framework, pull requests merged in 2023-11, with the labels that each got.

#2 content/getting-started: fix OCI URL for prometheus-postgresql-alerts-chart
  content/getting-started.md
Labels: documentation

#5 Fix additionalRuleLabels default type
  charts/prometheus-postgresql-alerts/values.yaml
  charts/prometheus-rds-alerts/values.yaml
Labels: bug

#10 Add security policy
  README.md
  SECURITY.md
Labels: documentation

#9 Aggregate metrics by labels
  .github/ISSUE_TEMPLATE/changes.md
  charts/prometheus-postgresql-alerts/values.yaml
  charts/prometheus-rds-alerts/values.yaml
Labels: bug

#13 Upgrade Hugo to 0.120.4
  .github/workflows/release.yaml
  docker-compose.yaml
  docs/hugo-upgrade.md
Labels: enhancement

#11 Add Prometheus standalone configuration file format
  charts/_source/templates/prometheusConfiguration.yaml
  charts/_source/templates/prometheusRules.yaml
  charts/_source/tests/prometheusRules_test.yaml
  charts/_source/tests/values/with_PrometheusConfigurationFileFormat.yaml
  charts/_source/values.yaml
  charts/prometheus-postgresql-alerts/values.yaml
  charts/prometheus-rds-alerts/values.yaml
  content/faq.md
  content/getting-started.md
Labels: enhancement

#12 Add prometheus unittests
  .github/workflows/test.yaml
  CONTRIBUTING.md
  Makefile
  charts/prometheus-postgresql-alerts/.helmignore
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLExporterDown.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLExporterErrors.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLExporterMissingScrapeErrorMetric.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLExporterScrapingLimit.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLInactiveLogicalReplicationSlot.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLInactivePhysicalReplicationSlot.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLInvalidIndex.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLLongRunningQuery.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLMaxConnections.yml
  charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLReplicationSlotStorageLimit.yml
  charts/prometheus-postgresql-alerts/values.yaml
  charts/prometheus-rds-alerts/.helmignore
  charts/prometheus-rds-alerts/prometheus_tests/RDSCPUUtilization.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSDiskSpaceLimit.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSDiskSpacePrediction.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSExporterDown.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSExporterErrors.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSExporterMissingMetrics.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSForcedMaintenance.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSIOPSUtilization.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSMemoryUtilization.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSNonCPUUtilization.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSPostgreSQLMaximumUsedTransaction.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSQuotaInstanceLimit.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSQuotaStorageLimit.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSReplicationLag.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSSwapUtilization.yml
  charts/prometheus-rds-alerts/prometheus_tests/RDSUnappliedParameters.yml
  charts/prometheus-rds-alerts/values.yaml
  scripts/check_prometheus_rules.sh
Labels: enhancement

#14 Fix search engine
  .github/workflows/release.yaml
  themes/patch_book.txt
Labels: bug
